### ISSUE TITLE
训练数据输入

### ISSUE THREAD

**Issue by yjhuasheng** [JinZhuXing/Fingerprint_PyTorch#2]
大佬，您好：
        感觉pytorch版本的训练数据导入好像有点问题，方便留个联系方式交流一下吗

**Comment by JinZhuXing** [comment]
非常感谢你对我的项目感兴趣。
请把您的想法用邮件发给我。(peace1019@126.com)
谢谢。

**Comment by yjhuasheng** [comment]
大佬，我对你使用cnn训练指纹很感兴趣，我也在小面阵指纹方面预研，这里面也遇到了很多疑问，方便加个微信多沟通吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JinZhuXing/Fingerprint_PyTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JinZhuXing/Fingerprint_PyTorch] 训练数据输入 (Issue #2)





 
非常感谢你对我的项目感兴趣。
 ***@***.***)
 谢谢。

**Comment by JinZhuXing** [comment]
谢谢，我也想加个微信。
![mmqrcode1665719946204](https://user-images.githubusercontent.com/15034343/195759940-d1f58305-99a9-4f0c-95cf-a3adae494ab5.png)
